version: "3"
services:
  triager:
    build: .
    env_file: .env
    command: python -m triager --bugs -c config.yaml --log --send-email

  ci_report:
    build: .
    env_file: .env
    command: python -m triager --ci -c config.yaml --log --send-email
