version: '3'
services:
  triager:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - MAINTAINERS=${MAINTAINERS}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-} #GITHUB TOKEN OPTIONAL

