version: '3'

services:
  triager:
    build: .
    volumes:
      - .:/app
    environment:
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - MAINTAINERS=${MAINTAINERS}
    command: python -m triager --bugs -c example-config.yaml --log --send-email

  ci_report:
    build: .
    volumes:
      - .:/app
    environment:
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - MAINTAINERS=${MAINTAINERS}
    command: python -m triager --ci -c example-config.yaml --log --send-email