---
orgs:
  - name: ansible-collections
    repos:
      - name: cisco.nxos
      - name: cisco.ios
      - name: cisco.iosxr
      - name: arista.eos
      - name: vyos.vyos
      - name: junipernetworks.junos
      - name: cisco.asa
      - name: ansible.netcommon
  - name: ansible
    repos:
      - name: ansible
        labels:
          - networking
          - needs_triage
      - name: pylibssh
maintainers:
  - name: John Doe
    email: john@doe.localhost
  - name: Jane Doe
    email: jane@doe.localhost
triager:
  email: testtriager@triage.example
  password: superSecretP@ssWorD
timedelta: 7
