# #Template for config.yaml

# # Organization name (used in email subject)
# organization_name: "Your Organization Name"

# # Workflow name (used for logging and debugging)
# workflow_name: "Your Workflow Name"

# # Path to repository configuration file (default: repo_config.json)
# repo_config: "repo_config.json"

# # Time delta (in days) for triaging issues
# timedelta: 14



# #Template for repo_config.json

# {
#   "organization1": {
#     "ci_and_bug_repos": [
#       "repo1",
#       "repo2",
#       "repo3"
#     ],
#     "bug_specific_repos": [
#       "repo4",
#       "repo5"
#     ]
#   },
#   "organization2": {
#     "ci_and_bug_repos": [
#       "repo6",
#       "repo7",
#       "repo8"
#     ],
#     "bug_specific_repos": [
#       "repo9",
#       "repo10"
#     ]
#   },
#   "organization3": {
#     "ci_and_bug_repos": [
#       "repo11",
#       "repo12",
#       "repo13"
#     ],
#     "bug_specific_repos": [
#       "repo14",
#       "repo15"
#     ]
#   }
# }

