#Sample Test Case for Ansible Tool Functionality

---
organization_name: "Ansible Networking"       

workflow_name: "tests.yml"                    

orgs:
  - name: ansible-collections
    ci_and_bug_repos:                         
      - name: cisco.nxos
      - name: cisco.ios
      - name: cisco.iosxr
      - name: arista.eos
      - name: junipernetworks.junos
      - name: cisco.asa
      - name: ansible.netcommon
      - name: ansible.snmp
      - name: ansible.security
      - name: ansible.network
      - name: ansible.utils
      - name: ibm.qradar
      - name: trendmicro.deepsec
      - name: splunk.es
    bug_specific_repos:                     
      - name: ansible.scm
      - name: vyos.vyos
      - name: frr.frr
      - name: openvswitch.openvswitch
      - name: community.yang
  - name: ansible
    bug_specific_repos:
      - name: pylibssh
  - name: redhat-cop
    ci_and_bug_repos:
      - name: network.interfaces
      - name: network.bgp
      - name: network.base
      - name: network.telemetry
      - name: network.vpn
      - name: network.acls
      - name: network.ospf
    bug_specific_repos:
      - name: network.backup

triager:
  address: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}

timedelta: 14

#github_token: ${GITHUB_TOKEN}  #Use GITHUB_TOKEN if you have a GitHub Actions workflow configured, otherwise comment this line out for unauthenticated requests."

maintainers: ${MAINTAINERS}

# github_token: 'Manually enter your github token here to make authenticated requests or comment this line to make unauthenticated API requests'




##Generic structure 
# ---
# organization_name: "Organization Name"        # Replace with your organization's name

# workflow_name: "workflow.yml"                 # Replace with your workflow file name, by default its tests.yml

# orgs:
#   - name: collections-group                   # Name of the first group of repositories
#     ci_and_bug_repos:                         # Repositories common between CI and bug tools
#       - name: collection1
#       - name: collection2
#       - name: collection3
#     bug_specific_repos:                       # Repositories only present in the bug tool
#       - name: collection4
#       - name: collection5
#   - name: another-org                         # Name of the second organization or group
#     bug_specific_repos:                       # Repositories only present in the bug tool
#       - name: repo1
#   - name: third-org                           # Name of the third organization or group
#     ci_and_bug_repos:                         # Repositories common between CI and bug tools
#       - name: repo2
#       - name: repo3
#     bug_specific_repos:                       # Bug tool-specific repositories
#       - name: repo4

# maintainers:
#   - name: Maintainer Name                     # Replace with maintainer details
#     email: maintainer@example.com             # Replace with actual email

# triager:
#   address: triager@example.com                # Replace with triager's email
#   password: secretPassword                    # Replace with an appropriate password

# timedelta: 14                                 # Time range in days for fetching relevant data (e.g., issues, pull requests), adjust as necessary

# github_token: 'your_github_token_here'        # Replace with your GitHub token or comment this line out to make unauthenticated API requests

