# #Template for config.yaml

# #Organization name (used in email subject)
# organization_name: "Ansible Networking"

# #Workflow name
# workflow_name: "tests.yml"

# #Time delta (in days) for triaging issues
# timedelta: 14
##Template for adding repos in Github secrets or .env file(for running locally)

# REPO_CONFIG= {
#   "ansible-collections": {
#     "ci_and_bug_repos": [
#       "cisco.nxos",
#       "arista.eos",
#       "junipernetworks.junos",
#       "cisco.asa",
#       "ansible.netcommon",
#       "ansible.snmp",
#       "trendmicro.deepsec",
#       "splunk.es"
#     ],
#     "bug_specific_repos": [
#       "ansible.scm",
#       "community.yang"
#     ]
#   },
#   "ansible": {
#     "bug_specific_repos": [
#       "pylibssh"
#     ]
#   },
#   "redhat-cop": {
#     "ci_and_bug_repos": [
#       "network.interfaces",
#       "network.bgp",
#       "network.base",
#       "network.ospf"
#     ],
#     "bug_specific_repos": [
#       "network.backup"
#     ]
#   }
# }
